import { MedusaService } from "@medusajs/framework/utils";
import { School } from "./models/school";
import { SchoolClass } from "./models/school-class";
import { AcademicYear } from "./models/academic-year";

/**
 * Service generated by MedusaService exposes CRUD methods for each registered
 * entity (createSchools, listSchools, retrieveSchool, updateSchools, deleteSchools, ...).
 *
 * Custom domain queries are added below.
 */
class SchoolModuleService extends MedusaService({
  School,
  SchoolClass,
  AcademicYear,
}) {
  /**
   * Active classes for a school, ordered by display_order.
   * Used by /pos/sync/pull and the school selector on the POS billing screen.
   */
  async listActiveClasses(schoolId: string) {
    return this.listSchoolClasses(
      { school_id: schoolId, status: "active" },
      { order: { display_order: "ASC" } },
    );
  }

  async getActiveAcademicYear() {
    const [year] = await this.listAcademicYears({ is_active: true });
    return year ?? null;
  }
}

export default SchoolModuleService;
